### ISSUE TITLE
k8s deployment file incorrect command

### ISSUE THREAD

**Issue by pindge** [EduardRosert/locust-wms-load-test#3]
## Problem
the current example https://github.com/EduardRosert/locust-wms-load-test/blob/master/k8s-locust-wms-test.yaml#L39-L40 returns `command /bin/bash` not found error

tried
```
      command: ["locust"]
      args: ["-f /app/wms-load-test/locustfile.py"]
```
the pod doesn't start and errors

the pod started correctly when both `command` and `args` were commented out.

## correct config (final solution)

```
        command: ["locust", "-f", "/app/wms-load-test/locustfile.py", "--host=$(WMS_SERVICE_URL)"]
        # args: [ "-f /app/wms-load-test/locustfile.py"]
```

note, without `$()` around `WMS_SERVICE_URL` the value is taken as `$WMS_SERVICE_URL.

**Comment by EduardRosert** [comment]
thank you for your comment, I've updated the k8s example manifest on dev branch
